FROM java:8-jre
WORKDIR /usr/src
COPY ./target/FavouritesModule-0.0.1-SNAPSHOT.jar FavouritesModule-0.0.1-SNAPSHOT.jar
#EXPOSE 8081
ENTRYPOINT ["java","-jar","/usr/src/FavouritesModule-0.0.1-SNAPSHOT.jar"]